### ISSUE TITLE
No such module 'LNPopupController'

### ISSUE THREAD

**Issue by iPrinz96** [BLeeEZ/amperfy#1]
i have a problem with the LNPopupController.
He can't find it.

Skype: iprinz96

würde mich über jede Hilfe freuen & ich würde mich auch sehr freuen  an dem Projekt mit machen zu dürfen.

Bin selbst dabei an einer App für Ampache zu tüfteln. Bin dabei auf das Project gestoßen & Design technisch hab ich mir das genau so vorgestellt.

**Comment by BLeeEZ** [comment]
Thanks for the remark. I had a problem with the git submodule. I pushed a fix. If you follow the instruction again, git submodule update should now actually clone the LNPopupController.
---
Freut mich wenn es dir gefällt. Ich bin für jede Art von Hilfe und/oder Anregungen dankbar.

**Comment by iPrinz96** [comment]
Again the same error.
I have download the LNPopupController and updated the path folder to the new Folder "LNPopupController-master/LNPopupController.xcodepro"
but don't work.. he can't find it

**Comment by BLeeEZ** [comment]
No such module 'LNPopupController' will only appear if the submodule under import/LNPopupController is empty. The submodule must be checked out to import/LNPopupController because the LNPopupController.xcodeproj in Amperfys project file is refering to import/LNPopupController/LNPopupController/LNPopupController.xcodeproj.

**Comment by iPrinz96** [comment]
https://imgur.com/xv0ZnYU

**Comment by BLeeEZ** [comment]
Glad to hear that it runs on your machine.
Best way to stay in contact with me is via email: amperfy@familie-zimba.de
I am happy to hear from you.
