### ISSUE TITLE
Airsonic support

### ISSUE THREAD

**Issue by plonibarploni** [BLeeEZ/amperfy#16]
I just installed this on my phone to listen to music on my [Airsonic](https://github.com/airsonic/airsonic) server, but while the song list does load (after a while), nothing actually plays. I also see no logs on the server.

**Comment by BLeeEZ** [comment]
Thank you for reporting this issue. I will set up an airsonic server on my Desk to test Ampfery with it.

**Comment by BLeeEZ** [comment]
I was able to reproduce your issue.
The issue is related to your airsonic configuration.
The user you are using with Amperfy needs the right to download files from airsonic:

![AirsonicAnswer](https://user-images.githubusercontent.com/17556018/108379390-27523000-7206-11eb-98b3-f75ae9b68751.png)

After you have granted the user this right you only need to delete the song cache in Amperfy.
This can be done in the Settings tab.
After the cache deletion you should be able to download and listen to your songs.
>Note: A library resync is not neccessary

**Comment by plonibarploni** [comment]
Thank you for testing it. I can confirm that your solution works, however other Airsonic/Subsonic clients work without this setting. Is there something you do differently?

**Comment by BLeeEZ** [comment]
I am using the REST API to get song. To save it for offline use I am directly downloading the file. I think this could be feature (song streaming) to implement in the future.

**Comment by BLeeEZ** [comment]
With this commit cadb638ba1538f35394e205b73d93fcdc042b330 not cached songs will be streamed. The download permission is not required to work with Amperfy.
