### ISSUE TITLE
Clear library cache without deleting downloaded songs

### ISSUE THREAD

**Issue by Bocom** [BLeeEZ/amperfy#168]
I used to have some broken tags in my Navidrome library (mojibake specifically) that have since been fixed, but the broken tags still show up in the library.

The artist that had broken tags just show empty lists, whereas the songs show up with the broken tags, but show the corrected tags while playing them.

I could delete the cache, but I would prefer to keep all the songs I have already downloaded, so it would be nice to get rid of these incorrect entries.

**Comment by sandersantema** [comment]
Although I'm not the developer I'm fairly certain this isn't possible or at least not by changing something about Amperfy itself. Again since I'm not the developer take the rest of this comment with a grain of salt.

First of all, there is no difference between the library cache and the downloaded songs, I believe those are the same so there is no separate cache to delete only the songs themselves which also contain the tags. 

Second, the subsonic api (or at least what's implemented by navidrome) doesn't seem to have a way to report what songs have changed metadata so Amperfy can't know.

Those two together make it so that the only solution here seems to be to delete all the songs with incorrect tags and download them again. If you know which songs these are you can create a playlist and delete/ download the whole playlist in one go.

**Comment by BLeeEZ** [comment]
I reworked the caching system. Now (b7d81da3291b8faf02b2c9cb9c2eb3d4544f131f) during a resync the already downloaded files (songs/podcast episodes/artworks) are reused. No need for downloading them again.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Did you have time test the feature? Is it behaving as you expected?
