### ISSUE TITLE
Support for self-signed certificates.

### ISSUE THREAD

**Issue by argus-core** [BLeeEZ/amperfy#18]
I run a Subsonic-compatible server (Navidrome) behind an Nginx reverse proxy with a self-signed certificate (Synology NAS). Login attempt from Amperfy fails with a "Login failed, Not able to login, please check credentials! message". There is no option to review or accept the certificate. Login works as expected when pointing Amperfy directly at Navidrome HTTP port.

- Navidrome is version 0.39.0 running in Docker on a Synology NAS running DSM 6.2.3-25426 Update 3
- Reverse proxy in use is the default Synology Ngnix
- Amperfy is the App Store version, I can't find a version number

**Comment by BLeeEZ** [comment]
Have you installed your self signed certificate as a root certificate in iOS settings as described [here](https://medium.com/collaborne-engineering/self-signed-certificates-in-ios-apps-ff489bf8b96e)?
New iOS apps which ignore certificate check do not pass the apple code review. So the solution is to install your certificate so the verification will not fail.
 I am thinking of a feature that Amperfy displays an error message if it can't connect to the server due to a failed certificate check.

**Comment by argus-core** [comment]
I've not tried that, thanks for the hint. An error message would be great, maybe even with a suggestion to install the self-signed cert on the device.

**Comment by BLeeEZ** [comment]
With this 85cb35fdba23bfdfa7298d43f52abd5beea40953 commit the user gets detailed error messages in the login view.
Certificate errors will be displayed as those.

**Comment by BLeeEZ** [comment]
Version 1.0.3 has been released on the App Store.
You should see an error message if you try to connect to a server with a self signed certificate.
Can you confirm this?

**Comment by argus-core** [comment]
Confirmed, attaching screenshot.

![navidrome](https://user-images.githubusercontent.com/11363546/109294402-08b2f100-7825-11eb-9dd4-0fbed5222951.jpeg)
