### ISSUE TITLE
Support requesting media in different formats (transcoding)

### ISSUE THREAD

**Issue by hugoghx** [BLeeEZ/amperfy#192]
Hey, just discovered this project and I find it pretty neat!

I'm using Navidrome as my music server and my songs are all `.ogg`. I understand AVPlayer doesn't support that format, and as expected, when trying to play my songs, none really work.

This introduces a pretty large ask for anyone who wants to use this app: Either have it in a format supported by AVPlayer, or you can't use the app.

I think it could be very helpful to have a setting in the app where we could configure what media format we request from the server. For example:

- Original
- MP3
- ...

I know Navidrome in particular supports transcoding media, however I'm not entirely sure what mechanism is used to deliver that transcoded media onto the client. I do, however, know it is possible, since substreamer does this -- Perhaps it's doing transcode on-device?

Either way, I think this would allow more people to be able to use the app in an easier way :)

Edit: The Subsonic API's [`stream` call](http://www.subsonic.org/pages/api.jsp#stream) seems to take a `format` parameter. This seems to be the mechanism to request a different media format from the server

**Comment by hugoamvieira** [comment]
I'm not very well versed in Swift or iOS dev, but here's some findings.

The functions that generate the calls for [stream](https://github.com/BLeeEZ/amperfy/blob/master/AmperfyKit/Api/Subsonic/SubsonicServerApi.swift#L220-L230) and [download](https://github.com/BLeeEZ/amperfy/blob/master/AmperfyKit/Api/Subsonic/SubsonicServerApi.swift#L208-L218) would need to take in the format the user chose in the settings.

We'd have to receive a `format` argument and pass that into `createAuthApiUrlComponent`, which would have to support adding that as a new parameter, much like we already do for `id`.

```swift
urlComp.addQueryItem(name: "format", value: format)
```

I'm not sure if the response body would change if this parameter is included on a `stream` or `download` call - but since Subsonic is designed to be REST, I'd expect it to stay the same, just with the media data transcoded to be in the requested format.

Since this seems to be the lowest layer present that interacts with the API directly, from here we just need to go up the stack until we have access to the user settings objects and add/change logic on the functions that request the stream/download from a Subsonic API server.

**Comment by stonie08** [comment]
I just want to add that this would be a usefull addition. Also the same call also supports a max-bitrate setting which would come in handy for a mobile device with data-caps, limited bandwidth, storage,.. So allowing for a certain number of file format and bit-rate settings would be great. Given that specifying format and bitrate seem to work in other subsonic-api compatible apps, this should be feasible as it is part of the protocol.

**Comment by JOJ0** [comment]
@BLeeEZ Hi, I tried switching from Navidrome to Ampache only for the possibility to download and transcode using Amperfy.

Now Ampache brought me into a hell load of other problems and I'm not sure I want to further go down that path...

Now, I somehow suppose you are an Ampache user and download+transcode with Subsonic servers might not be on your top prios list but is there any chance you might want to look into it? It's actually the one thing preventing me from using Amperfy as my go to app for offline listening. Just here to ask :-)

**Comment by BLeeEZ** [comment]
I am interested in this feature and I put on the list for the next version.

**Comment by BLeeEZ** [comment]
It is implemented in 271612662ea43c4dcbe646cd060a545c430ec902.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-22 at 21 03 21](https://github.com/BLeeEZ/amperfy/assets/17556018/8ca2b358-7677-4c0e-b2da-bf67d13c1313)

**Comment by yuygfgg** [comment]
> It is implemented in [2716126](https://github.com/BLeeEZ/amperfy/commit/271612662ea43c4dcbe646cd060a545c430ec902). ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-22 at 21 03 21](https://private-user-images.githubusercontent.com/17556018/324581197-8ca2b358-7677-4c0e-b2da-bf67d13c1313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjA0ODQsIm5iZiI6MTcxNTA2MDE4NCwicGF0aCI6Ii8xNzU1NjAxOC8zMjQ1ODExOTctOGNhMmIzNTgtNzY3Ny00YzBlLWIyZGEtYmY2N2QxM2MxMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA1MzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNDYyOGQ2OTVmMzFmMzUyNzY4NWFhYzljZjc0ODQ2NTlhNTAyOTc5NjYwYWMxMDc3NjQ3MTBmMjQyZjdmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZIYdpvruip_GD07wft0TfrqeWPE79_miipTHBpSAio)

Is this feature available in the latest release version? I can't find the setting

**Comment by BLeeEZ** [comment]
This feature is currently not available via TestFlight. I will notify here when a new Beta is available with this feature.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Did you have time test the feature? Is it behaving as you expected?

**Comment by brokoler** [comment]
> Did you have time test the feature? Is it behaving as you expected?

Joined testflight since I had the same feature request in my mind and was surprised about the added featurein the newest beta.

My feedback:
- Transcoding works when set to 320kbps or .mp3
- Downloaded files are much reduced in size, FLAC files with around 60 MB per song were reduced to around 8MB per song
- For the user it's complicated to verify the bitrate -> Could we get an option to show the bitrate for the currently played song?
- Would be great if Transcoding for downloads (Caching) could be set to 320kbps and a second option would allows unlimited bitrate when streamed via WiFi. That way downloads would be small in size when on the go, but at home when streamed to audio equipment the bitrate would be as high as possible

Really a beautiful app and I'm excited what features are introduced in future.
Gonna beta test every version from now. Thank you!

**Comment by WilsontheWolf** [comment]
> Did you have time test the feature? Is it behaving as you expected?

I joined the test flight and have been using it all week. It's been working really good, but I had some issues when streaming some songs (which I don't normally do, but was doing because I invalidated my entire cache). When streaming music, I found that it does not show the end time in the player (and as a consequence, I can't seek and the Lock Screen doesn't show progression).
 I've also had it where a song that was streaming randomly started playing from the beginning, but the playback time didn't go back to zero or anything. Only happens when streaming and I'm not sure how to replicate, but it seemed to be more likely to happen on longer songs. 
 downloaded songs have been working flawlessly, and I can actually listen to music formats Amperfy doesn't support. 
 I've also noticed some weird behaviour with scribbling. I haven't dug into exactly what happened, I'll try to figure that out later.

**Comment by stonie08** [comment]
This might be a Navidrome issue in the end, but I also noticed that it seems like server transcoding might always be overwritten by the settings for some reason. I tried to set the session to something obviously low and bad (32kbps mp3) and Amperfy to its default limits and settings, and it seemed like the audo was fine. Can anyone confirm?

**Comment by BLeeEZ** [comment]
I think you can limit the bitrate on server side.
