### ISSUE TITLE
Live Scrobbling

### ISSUE THREAD

**Issue by Jaffex** [BLeeEZ/amperfy#217]
When listening to a song with other players like play:Sub, substreamer or the navidrome web interface itself, when listening to a song, it immidiately appears as scrobbling on last.fm like so:
![image](https://github.com/BLeeEZ/amperfy/assets/31133207/c294fd66-9709-4bb5-aa39-c55ef605de09)

When listening via Amperfy, the song does not display that state but only shows up once it has reached the criteria for "has been listened to".

Would it be feasible to implement this in amperfy as well?

**Comment by BLeeEZ** [comment]
This whole scrobble topic is quite complex. You opend https://github.com/BLeeEZ/amperfy/issues/218 too. I want to answer both requests here:

Scrobbling is handled in slightly different on each music server.
Amperfy will only send scrobble information to server if the song is played from cache and is played long enough. If the song is streamed no scribble information is sent at all. 
Somer server account streaming as currently playing, this is why no scrobble information is not send. Navidrom doesn't count streamed songs as currently played, which is from point of view not correct.
To work absolutely correct on each music server instance Amperfy must be differently configured for each music server type, version (due to changes in the scribble mechanic on server) and so on. I only differentiate between API types in Amperfy (Ampache API/ Subsonic API).
I will stick with the current scrobble system in Amperfy since it is compatible with most music servers.

**Comment by BLeeEZ** [comment]
I added an option in the settings to decide if Amperfy should scrobble streamed items too:
![Simulator Screenshot - iPhone 15 - 2024-02-20 at 19 43 10](https://github.com/BLeeEZ/amperfy/assets/17556018/c58e7628-4ad2-4670-ba79-7b48b61753f5)

**Comment by BLeeEZ** [comment]
Now playing is implemented in e4e864c8d69f764d37c6ec7eafa883934cbc214d.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by Jaffex** [comment]
Just testing out, and even though it seems 1.2.1 has some issues in testflight right now, the live scrobbling seems to work!

**Comment by umbilicalbungee** [comment]
On version 2.2.2 Build 22 I'm not seeing the option to Scrobble streamed songs. Did that get removed?
