### ISSUE TITLE
Amperfy crashes when in airplane mode / disconnected

### ISSUE THREAD

**Issue by bietiekay** [BLeeEZ/amperfy#244]
I was let down by Amperfy when I preloaded lots of my music library and went on a 15 hour flight. Only to find Amperfy to crash when my phone was in Airplane mode / not connected "correctly".

Please please make it work and not just crash - it opened and closed whenever launched. Can be replicated when certain network conditions are met (airplane mode / no correct network but maybe iOS says there is network....)

**Comment by BLeeEZ** [comment]
Have you tried "Offline Mode" in Settings. Is it then still crashing?

**Comment by bietiekay** [comment]
Yes. Switched to offline when I was back at home - still crashed when network was bad/disconnected.

Also: While travelling I had the app crash immediately after starting it - no time to switch to the offline mode because there was no way to get to the settings in the app. The Settings page of the System Settings does not offer the offline mode.

**Comment by BLeeEZ** [comment]
What Amperfy version and what server are you using?

**Comment by bietiekay** [comment]
Amperfy 1.1.5 and Subsonic 11.0 

Since there was no internet available (in a plane) there was no connection to subsonic possible.

**Comment by Samaze123** [comment]
I have the same issue here. My server crashed so I had no connection to it and I can't listen more that 30 sec before Amperfy crash. Even in offline mode.

**Comment by BLeeEZ** [comment]
Amperfy has two backend APIs (Subsonic and Ampache). I asked to know which API could. be responsible for the crash.

I tested a lot of different network conditions and I am currently not able to reproduce this issue.
Could you please install the Beta via TestFlight (https://github.com/BLeeEZ/amperfy/issues/25).
TestFlight allows the testers to send crash reports when one occurs. This would help to find the root cause.
I did some API changes in v1.2.0 (3) too, maybe this already fixed the crash.

Can you tell me how much background song sync percentage ("Settings"->"Library"->"Background Song Sync") did you have when it crashed?

**Comment by Samaze123** [comment]
For me the beta version fixes the issue and don't crash anymore. Thanks !
