### ISSUE TITLE
Still the same issues are present a year later: song stops randomly, repeats etc

### ISSUE THREAD

**Issue by greenfishgit22** [BLeeEZ/amperfy#322]
Excellent application, i'm very grateful. However the same issues I had with the app a year ago are still here.

No matter if it's my own WIFI or cellular. No matter if it's pure stream or transcoding I have these issues:

Playing a song it will randomly stop at x time and either repeat the same song again or skip ahead or backwards or completly shift album. Using my navidrome webclient I don't have these issues. But I very much prefer to have amperfy as my main client instead. 

Why is this happening, can it be fixed?

Thank you

**Comment by BLeeEZ** [comment]
Duplicate to https://github.com/BLeeEZ/amperfy/issues/305. There you can find the current status of the bug.

**Comment by BLeeEZ** [comment]
With 1e6f22917f53d406d1815b23c8e4609a0809d2d0 I introduced additional logging. You can now see playback stalling and player errors in the event log: Settings -> Support -> Event Log. I am still not able to reproduce this wrong behavoir on none of my devices/simulators. I hope you can provide me the event log after this playback error occured in order to be able to fix this issue.
