### ISSUE TITLE
[Features] macOS feedback (Volume slider, Remember window size)

### ISSUE THREAD

**Issue by BLeeEZ** [BLeeEZ/amperfy#336]
1. It would be great if the app could remember the window size. Currently, every time I resize the window and reopen it, it reverts to the default size. Also, the album list grid doesn’t automatically adjust to fill the window. Since the album cover sizes are fixed, when the window is slightly narrowed, only two columns of albums are displayed, leaving a large gap in the middle.

2. It would be helpful to have independent volume control. Currently, the app’s volume is tied to the system volume, which is not always convenient. Having the option to adjust the volume separately would be appreciated.

**Comment by Schlaubischlump** [comment]
Do you have "Close windows when quitting an application" enabled? I think apple changed the default for that flag at some point. Otherwise the app will create a new window on each restart and thereby forget its size. When the flag is disabled, the window will restore the size on my machine.

<img width="478" alt="Screenshot 2024-10-17 at 09 40 30" src="https://github.com/user-attachments/assets/ed3b3a3b-35c1-49f3-90e2-58ca48f6237c">

**Comment by BLeeEZ** [comment]
The listed features are a collection of user feedback I received via TestFlight/eMail.

1. I unchecked the option you mentioned but the window still does not remember its size. Is there some other trick we could use or do we need to save the size in a setting variable and need to set it on start?

**Comment by Schlaubischlump** [comment]
Strange that it does not work for you... Maybe it is OS version-specific. I don't know of any other trick. I think the only remaining option is to save and restore the size manually.

**Comment by Schlaubischlump** [comment]
> Also, the album list grid doesn’t automatically adjust to fill the window. Since the album cover sizes are fixed, when the window is slightly narrowed, only two columns of albums are displayed, leaving a large gap in the middle.

I opened a pull request to fix this issue.
