### ISSUE TITLE
[Bug]: Number of albums reported for artist is wrong

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#56]
In the artist menu a lot of the artist in my library are listed as having 0 albums even though amperfy shows me albums when clicking on the artist.

**Comment by sandersantema** [comment]
It might not be an amperfy bug but rather something on the side of ampache: https://github.com/ampache/ampache/commit/2eae859fa9ea7d6f95d37d8b38f99ef2213c4acc

I'll try updating to the latest ampache and see if that fixes it.

**Comment by PaulWalkerUK** [comment]
When I've seen this on mine, it seems to be when an artist is only listed as an "artist" rather than an "album artist". I don't know what the "correct" behaviour should be, but I don't mind too much the way it is, it kinda tells me that the artist doesn't have any albums in their own name

**Comment by BLeeEZ** [comment]
This issue is related to missing information. When the artist has not yet tapped on (no sync of the artists has happen yet) I display the information provided by Ampache/Subsonic. The server returns the count of albums in which the requested artist is the only artist (ignoring "album artists). Exactly what @PaulWalkerUK mentioned. I personally prefer to display all albums that have any relation with the requested artist. Is this why the album count number are different.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
