### ISSUE TITLE
`1.0.6 (1)` Crashes immediately after start

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#61]
Using iPhone SE 2nd ed. and iOS 14.3. I've reported the crash trough testflight but unfortunately without being able to add any text since Apple's own stuff is bugged too and the keyboard blocks the information field. Except that in the case of Apple this bug isn't excusable ;) But you should be able to identify it by my email: `sanderbartsantema2 at google mail dot com`.

EDIT:

FYI if you're experiencing this bug you can always rollback to the previous version using the testflight app.

**Comment by BLeeEZ** [comment]
Does the app always crash or sometimes?

**Comment by sandersantema** [comment]
Always

**Comment by BLeeEZ** [comment]
I took a look at your crash log. And the error states that the library migration failed. From which app version did updated to 1.06(1)? v1.0.5 (6)?

**Comment by sandersantema** [comment]
1.0.5 (5) never got (6)

**Comment by BLeeEZ** [comment]
I checked it. I am sorry to tell you that the only way solve this issue is to delete Amperfy and install it again.
From 1.0.5 (5) to 1.0.5 (6) a change to the underlying database has been made. Previously a fuzzy migration took place. With that only beta version to beta version migration works or major release to major release. I already fixed this issue with a new migration strategy. With that it is possible to update the database to the latest release no matter on which the old version was. During this specific beta release no dedicated version has been created. So the update from 1.0.5 (5) to 1.0.5 (6) and then to 1.0.6 (1) would have worked.
The only solution to this problem, due to fact that a version downgrade is not possible, is to delete the app and reinstall it again. Sorry for that.

**Comment by sandersantema** [comment]
No worries, I don't mind reinstalling for some nice new features :) and it's to be expected since these are betas after all. Furthermore, if it weren't for Apple's terrible release mechanisms it wouldn't have been a problem anyways. I've reinstalled and it's all working fine now :)
